Orders with multiple random qualities
hpi-epic/pricewars-producer pull request #9
Opened 2018-08-27 10:19 UTC by CarstenWalther

Previously, a merchant ordered a specific amount of a random product with a random quality. With this PR, merchants order a specific amount and get items of one random product type but of different qualities. The qualities are chosen uniformly randomly from the available qualities.

Unit price, fixed order costs and product stock is now unique for each product type. Previously these attributes were unique for each product type and quality combination. This change has the advantage, that merchants can calculate how much an order will cost them.

The producer API changed. E.g. an order contains a list of products instead of one product. Existing merchants won't work with these changes. I'll create a pull request with updated example merchants. There will also be a change in the analytics repository.

Currently it's not possible to inspect or change the producer configuration in the management UI. I'll need to change the management UI as well to work with the new product information format.

If a merchant orders a product, he will receive an order with the following attributes:

- product id
- product name
- billing amount
- fixed cost
- unit price
- stock
- left in stock
- list of products

And products in that order have the following attributes:
- uid
- product id
- name
- quality
- amount
- time to life
- start of lifetime
- signature

2018-08-27 10:37 UTC, CarstenWalther commented
This pull request is work in progress. Please do not merge yet

2018-08-30 16:29 UTC, CarstenWalther commented
I updated the communication between producer and management UI and removed some API routes that are not used. For now, I done with this pull request.

2018-09-04 11:59 UTC, Bouncner requested changes

2018-09-04 11:59 UTC, Bouncner commented on controllers/models/Products.js
> +            name: 'CD_1',
Can we rename to `Product #1`?

2018-09-04 11:59 UTC, Bouncner commented on controllers/models/Products.js
> +            product_id: 1,
Can we find a solution that does not require the repetition of the ID?

2018-09-06 16:48 UTC, Bouncner approved these changes

2018-10-02 12:03 UTC, merged